nbc-react-3rd-final-project-a5/yolocean

src/app/layout.tsx, src/lib/Portone.tsx
- 결제 : NHN KCP 사용 (실결제가 되지 않는 PG에서 가장 다양한 카드결제를 지원) 
- 인증 : KG 이니시스 (하나뿐인 인증 방식)
=> [feat/payment] portone sdk 를 이용한 인증 및 결제

src/app/product/page.tsx, src/components/Tab.tsx
activeTab:선택된 탭
onClickTabFn: 클릭시 실해할 함수 (기본적으로 1번인자는 index임)
tabs: 전달한 tab이름들
=> Feat/tab Tab컴포넌트 생성

src/app/product/page.tsx, src/components/Card.tsx, src/components/Tab.tsx
=> Feat/card 상품카드 컴포넌트 만들기

src/app/layout.tsx, src/app/product/page.tsx, src/components/ContextInput.tsx, src/components/Input.tsx
formContext를 활용할경우 사용할수있는 컴포넌트와 그렇지 않은 컴포넌트를 생성하였습니다.
label?: 라벨명입니다.
name: register의 이름입니다.
placeholder: 제곧내
required?: 필수입력사항인 경우 string을 넣으면 해당input의 값이 입력되지않으면 발생할 메시지입니다.
pattern?: 값의 형태를 정의해주시면됩니다.
errorMessage: 올바르지 않은 값이 들어올경우 보여줄 에러입니다.
validate?: 함수를 보내주시면됩니다.(비밀번호 확인)
type: 인풋의 타입입니다.
register: UseFormRegister; 재곧내로 useForm에서 통짜로 넣어주시면됩니다.
formStateErrors: Record<string, any>; 재곧내로 useForm에서 통짜로 넣어주시면됩니다.
observerValue?: string; 감시할값입니다 (ex:비밀번호체크시 "password")
setError: any; 재곧내로 useForm에서 통짜로 넣어주시면됩니다.
watch: any;재곧내로 useForm에서 통짜로 넣어주시면됩니다.
clearErrors: any;재곧내로 useForm에서 통짜로 넣어주시면됩니다.
=> Feat/input 재사용가능한 input 컴포넌트 생성

src/app/admin/product/page.tsx, src/app/admin/store/PostCode.tsx, src/app/admin/store/page.tsx, src/app/admin/store/useMap.ts, src/app/api/region/route.ts, src/app/api/store/route.ts, src/app/layout.tsx, src/hooks/useCategory.tsx, src/hooks/useImageFile.ts, src/hooks/useRegion.ts, src/store/address.ts, src/store/addressStore.ts, src/types/db.ts, src/types/supabase.ts
Prodcut 등록 페이지 수정
- useCategory 훅을 사용해 category fetch
Store 등록 페이지
지점명, 카테고리 선택
주소 검색하기 클릭 시 주소 검색 창이 새로 나옵니다.
주소 선택하면 아래에 선택한 주소가 보입니다. (readOnly라서 수정 불가합니다.)
지점 등록하기 버튼 클릭 시 지점이 등록됩니다.
=> [Feat/form] Product 등록 페이지 수정 & Store 등록 페이지 추가

src/app/admin/product/page.tsx, src/app/category/[categoryId]/CategorySection.tsx, src/app/category/[categoryId]/page.tsx
range bar를 조종해 할인률을 선택할 수 있습니다.
=> [Feat/form] Product 등록 페이지 할인률 추가

src/app/admin/product/page.tsx, src/app/category/[categoryId]/SelectOffice.tsx, src/store/officeStore.ts
카테고리 모달에서 지역 선택 시 전역으로 저장됩니다.
useOfficeStore의 regionId로 사용 가능합니다.
=> [Feat/user] Region id 전역상태관리

src/app/admin/product/page.tsx, src/app/category/[categoryId]/SelectOffice.tsx
=> [Feat/category] category 모달 스타일 수정 (#34)

src/app/globals.css, tailwind.config.ts
=> style:전역스타일 추가 및 tailwiconfig 기본테마 수정

src/components/layout/Footer.tsx
- marginTop 200px
- 의미없는 flex-row 제거
=> [feat/layout] footer 컴포넌트 style 변경

src/app/cart/page.tsx, src/app/users/[userId]/EditUserInfo.tsx, src/app/users/[userId]/UserInfo.tsx, src/app/users/[userId]/page.tsx
=> [feat/user] 마이페이지 프로필 스타일 추가

src/app/users/[userId]/EditUserInfo.tsx, src/components/layout/PageBreadCrumb.tsx
=> [feat/user] 마이페이지 프로필 스타일 수정, BreadCrumb 스타일 수정

src/app/category/[categoryId]/CategoryHeader.tsx
카테고리 페이지 브레드크럼브 부분 스타일 수정했습니다!
=> [feat/category] 카테고리페이지 상단 스타일 수정(#34)

src/app/category/[categoryId]/CategorySection.tsx, src/app/page.tsx, src/components/CardLists.tsx
메인페이지 컴포넌트 구성했습니다.
메인페이지 카드리스트 컴포넌트 작성했습니다. 
카테고리 페이지 카드리스트 부분 컴포넌트로 대체했습니다.
=> [feat/main] 메인페이지 컴포넌트 작성

src/app/api/product/[productId]/route.ts, src/app/category/[categoryId]/CategorySection.tsx, src/app/category/[categoryId]/[productId]/Info.tsx, src/app/category/[categoryId]/[productId]/ShareModal.tsx, src/app/category/[categoryId]/[productId]/page.tsx, src/components/Tab.tsx, src/hooks/useReview.ts
=> Feat/product 클립보드 복사기능 추가 , Tab상단 고정 및 현재 보고있는 탭에따라 active시키도록 수정

src/app/admin/product/page.tsx, src/app/api/review/route.ts, src/app/page.tsx, src/hooks/index.ts, src/hooks/useCategory.ts, src/types/db.ts
홈화면 리뷰 추가했습니다.
React Query 사용해 카테고리 불러오는 부분 수정했습니다.
=> [feat/main] 메인컴포넌트 작업중 & category useQuery 수정

src/app/category/[categoryId]/CategoryHeader.tsx
기존에 주소가 없을 때도 위치 아이콘이 나오는 부분 수정했습니다.
=> [feat/category] 주소 선택시에만 아이콘 렌더링 (#34)

src/app/auth/SignIn.tsx, src/app/auth/SignUp.tsx, src/app/auth/page.tsx, src/components/layout/Header.tsx, src/types/supabase.ts
- 회원가입 시 전화번호 입력 (+supabase에 반영)
- 회원가입/로그인 브레드크럼브 적용 및 Section  적용
- 디자인에 맞게 css 수정
=> feat,style: 회원가입 시 전화번호 입력 및 auth페이지 스타일링 (#81)

src/app/layout.tsx, src/components/layout/Footer.tsx, src/components/layout/PageControlBtnGroup.tsx, src/data/footerData.json
- 페이지 컨트롤 버튼 생성
- footer 링크 수정
=> [feat/layout] 페이지 컨트롤 버튼 생성

src/app/auth/[find]/FindID.tsx, src/app/auth/[find]/FindPW.tsx, src/app/auth/[find]/ResultPW.tsx, src/service/sercretbase.ts, src/service/supabase.ts
- 비밀번호 재설정시 supabase secret api key가 필요해서 env.local. 수정 및 secretbase.ts를 추가했습니닷.
- 본인인증 추가 필요~!
=> [Feat/find] pw 재설정

src/app/api/products/[categoryId]/route.ts, src/app/api/qna/product/[productId]/route.ts, src/app/api/review/products/[productId]/route.ts, src/app/category/[categoryId]/[productId]/(article)/Description.tsx, src/app/category/[categoryId]/[productId]/(article)/Infomation.tsx, src/app/category/[categoryId]/[productId]/(article)/Qna.tsx, src/app/category/[categoryId]/[productId]/(article)/Review.tsx, src/app/category/[categoryId]/[productId]/CommonGuide.tsx, src/app/category/[categoryId]/[productId]/Info.tsx, src/app/category/[categoryId]/[productId]/page.tsx, src/components/Pagenation.tsx
=> feat:pagenation컴포넌트 Link로 수정 , 페이지네이션 (Qna만 완료 )

src/app/api/review/products/[productId]/route.ts, src/app/category/[categoryId]/CategorySection.tsx, src/app/category/[categoryId]/[productId]/(article)/Qna.tsx, src/app/category/[categoryId]/[productId]/(article)/Review.tsx, src/app/category/[categoryId]/[productId]/ControlForm.tsx, src/app/category/[categoryId]/[productId]/Info.tsx, src/app/page.tsx, src/components/Card.tsx, src/components/Pagenation.tsx
=> Feat/product pagenation 클라이언트컴포넌트로 수정

src/app/api/cart/[id]/route.ts, src/app/api/category/[categoryId]/route.ts, src/app/api/store/[regionId]/route.ts, src/app/api/users/[userId]/route.ts, src/app/cart/CartItem.tsx, src/app/cart/page.tsx, src/app/category/[categoryId]/[productId]/StockTable.tsx, src/app/page.tsx, src/app/payment/page.tsx, src/app/payment/paymentSuccess.ts, src/app/receipt/Receipt.tsx, src/app/receipt/page.tsx, src/components/DragDropImageInput.tsx, src/hooks/useCart.ts, src/types/db.ts
빌드 테스트 했습니닷
속도가 아주 빨라졌습니다
라이트하우스 점수도💯 
빌드 나이쓰 👍 
++빌드와 관련없이 수정된 부분 많습니다,, 그냥 제 개인 작업사항을 따로 커밋을 안해서,,
=> build test

src/app/api/cart/[id]/route.ts, src/app/page.tsx, src/types/supabase.ts
=> [Feat/main] supabase 타입 수정

src/app/api/review/fixed/route.ts, src/app/category/[categoryId]/page.tsx, src/app/page.tsx, src/types/db.ts
api/review/fixed 디렉토리에 GET 함수 작성
메인페이지 fixed_review데이터 불러오기
=> main 페이지 리뷰 작업

src/app/api/product/[productId]/route.ts, src/app/api/storage/banner/[bannerName]/route.ts, src/app/product/[productId]/(article)/Qna.tsx, src/app/product/[productId]/View.tsx, src/app/product/[productId]/page.tsx, src/app/users/[userId]/(tabContent)/RentItem.tsx, src/app/users/[userId]/(tabContent)/UserQnaList.tsx, src/app/users/[userId]/(tabContent)/UserRentList.tsx, src/app/users/[userId]/(tabContent)/UserReservationList.tsx, src/app/users/[userId]/UserInfoSection.tsx, src/app/users/[userId]/UserTab.tsx, src/app/users/[userId]/page.tsx, src/components/review/ReviewBtnGroup.tsx, src/service/supabase.ts, src/service/table/banner.ts, src/service/table/product.ts
- api : api 추가
- service : getBanner 함수 추가
=> [feat/storage] banner 데이터 가져오기

src/app/category/[categoryId]/page.tsx, src/app/page.tsx, src/app/product/[productId]/(article)/Review.tsx, src/components/Carousel.tsx, src/components/pulse/AvatarPulse.tsx, src/components/pulse/CardPulse.tsx, src/components/pulse/ImgPulse.tsx, src/components/pulse/ReviewPulse.tsx
다른종류의 pulse가 필요한경우
img, avatar 등을 조합해서 컴포넌트를 만드시면됩니다.
=> Feat/pulse 로딩 스피너와 병행해서 사용할 pulse컴포넌트를 제작하였습니다.

src/app/product/[productId]/View.tsx, src/middleware.ts, src/service/supabase.ts
미들웨어를 통해 api/user users 두경로로 접근 시 액세스 토큰 과 params의 uid의 유효성 검사를추가하였습니다.
=> Feat/middleware 미들웨어를 통해 로그인한 사용자의 토큰을 검사하도록 작업중.

src/app/api/storage/banner/route.ts, src/app/page.tsx, src/components/Banner.tsx, src/middleware.ts
=> [feat/main] 메인 페이지 베너 추가 

src/app/users/[userId]/UserInfo.tsx, tailwind.config.ts
=> [style/mobile] 

src/app/users/[userId]/EditUserInfo.tsx, src/components/auth/AuthBtn.tsx, src/components/category/HeadCategory.tsx, src/components/layout/Header.tsx, src/components/layout/HeaderSearch.tsx, src/components/layout/mobile/MobileHeader.tsx, src/components/layout/mobile/MobileSearch.tsx, tailwind.config.ts
=> [style/header] 모바일 헤더 스타일링

src/components/CustomButton.tsx, src/components/CustomLink.tsx
[공통 prop]
children,
onClick,
disabled
size
fontWeight
color
isOutline
isFull
[CustomLink prop]
href
replace
scroll
prefetch
=> [feat/button] 커스텀 버튼 및 링크

src/app/users/[userId]/(tabContent)/RentItem.tsx, src/app/users/[userId]/(tabContent)/UserPagenation.tsx, src/app/users/[userId]/(tabContent)/UserQnaList.tsx, src/app/users/[userId]/(tabContent)/UserReviewList.tsx, src/app/users/[userId]/UserInfo.tsx, src/app/users/[userId]/UserTab.tsx, src/components/Pagenation.tsx, src/service/table/qna.ts, src/service/table/review.ts
=> [style/mypage] 마이페이지 수정입니다.

src/app/swiper.css, src/app/users/[userId]/(tabContent)/UserQnaList.tsx, src/app/users/[userId]/(tabContent)/UserRentList.tsx, src/app/users/[userId]/(tabContent)/UserReservationList.tsx, src/app/users/[userId]/EditUserInfo.tsx, src/components/CardCarousel.tsx, src/components/Carousel.tsx, src/components/pulse/ProfilePulse.tsx
=> [style/main product] 메인페이지 케러셀 수정

src/components/layout/Footer.tsx, src/components/layout/PageControlBtnGroup.tsx
=> [style/layout] 

src/app/category/[categoryId]/CategoryHeader.tsx
=> [style/category_modal] 위치선택 버튼 반응형 디자인 추가

src/app/customer/page.tsx, src/middleware.ts
미들웨어 설정 완료했습니다.
이제 사용자 외에 다른 사용자 페이지 접근불가,
로그인 안하고 로그인 후 이용가능한 서비스 접근불가,
어드민 페이지 접근 불가입니다.
=> feat:미들웨어 설정 완료

src/components/Tab.tsx
=> style: tab 수정(#124)

src/app/payment/[userId]/SuccessModal.tsx, src/app/payment/[userId]/page.tsx
=> [refact/cart]: 약관체크 버튼 수정 및 테스트 결제 명시

src/app/cart/[userId]/page.tsx, src/app/search/page.tsx
=> [style/search] cart, search 스타일 수정

src/app/layout.tsx, src/app/product/[productId]/ShareModal.tsx, src/lib/KakaoScript.tsx
=> feat/kakao 카카오공유하기 추가(env변경)

src/app/auth/SignIn.tsx, src/app/auth/SignUp.tsx, src/app/auth/[find]/FindID.tsx, src/app/auth/[find]/FindPW.tsx, src/app/category/[categoryId]/CategoryHeader.tsx, src/app/search/[searchWord]/page.tsx, src/app/users/[userId]/page.tsx
=> [fix/breadcrumb] breadcrumb 수정

src/app/auth/SignUp.tsx, src/app/auth/page.tsx, src/app/globals.css, src/app/layout.tsx, src/app/payment/[userId]/page.tsx, src/components/layout/PageControlBtnGroup.tsx, src/lib/portone.ts
- 모바일 시 회원가입이 되지않던 문제를 해결했습니다.
- 스크롤 스무스도 추가했습니다.
=> [fix/payment] 모바일 회원가입 오류 수정 

src/app/api/user/[userId]/cart/route.ts, src/app/api/user/[userId]/rent/route.ts, src/app/payment/[userId]/SuccessModal.tsx, src/app/payment/[userId]/page.tsx, src/app/users/[userId]/(tabContent)/RentItem.tsx, src/types/db.ts, src/types/supabase.ts
- 렌트 테이블에 수정 (우선 rentlog라는 테이블 새로 만들어서 작업)
- 결제 / 마이페이지에서 rentlog에 맞춰 업로드 / 불러오기
- 카트에서 정보 읽어올 때 rent_date가 오늘 이전의 것은 불러오지 않음
=> [refact/rent] 렌트 테이블 수정

src/app/api/certification/payment/route.ts, src/app/payment/[userId]/page.tsx, src/lib/portone.ts
모바일 결제 시 리다이렉션 문제로 결제가 안되던 문제를 해결하였습니다.
=> [fix/payment] 모바일 결제 오류 수정

src/app/form/(form)/QnaForm.tsx, src/app/form/(form)/ReviewForm.tsx
리뷰, 폼 작성 페이지에서 취소 버튼 클릭 시 뒤로 가기
=> [fix/form_button] 취소 버튼 클릭시 뒤로가기

package-lock.json, package.json, src/app/category/[categoryId]/CategorySection.tsx, src/app/form/(form)/QnaForm.tsx, src/app/form/(form)/ReviewForm.tsx, src/app/product/[productId]/ControlForm.tsx
리뷰작성,
Qna작성,
리뷰수정,
Qna수정,
장바구니담기,
구매하기
lodash라이브러리 설치
=> Feat/debounce 사용자 조작이 필요한버튼에 디바운싱을추가했습니다.

src/app/form/(form)/QnaForm.tsx, src/app/form/(form)/ReviewForm.tsx, src/app/product/[productId]/ControlForm.tsx
동작실행까지 걸리는 시간을 줄였습니다.(0.5초 => 0.3초)
=> Feat/debounce 단순 시간 수정

src/app/form/(form)/QnaForm.tsx, src/app/form/(form)/ReviewForm.tsx, src/app/form/page.tsx, src/hook/useImageInput.ts, src/service/table/qna.ts, src/service/table/review.ts
=> Refact/form useMutation 및 uesEffect로 스피너 제어하던 부분을 수정

src/app/api/revalidate/product/[productId]/qna/route.ts, src/app/api/revalidate/product/[productId]/review/route.ts, src/app/customer/page.tsx, src/app/form/(form)/QnaForm.tsx, src/app/form/(form)/ReviewForm.tsx, src/app/form/page.tsx, src/app/product/[productId]/(article)/Qna.tsx, src/app/product/[productId]/(article)/Review.tsx, src/app/product/[productId]/Info.tsx, src/components/Pagination.tsx, src/components/review/ReviewBtnGroup.tsx
=> Refact/form pulse안나오던 버그 수정

README.md, src/app/api/revalidate/product/[productId]/qna/route.ts, src/app/api/revalidate/product/[productId]/review/route.ts, src/app/auth/SignIn.tsx, src/app/customer/page.tsx, src/app/form/(form)/QnaForm.tsx, src/app/form/(form)/ReviewForm.tsx, src/app/form/page.tsx, src/app/product/[productId]/(article)/Qna.tsx, src/app/product/[productId]/(article)/Review.tsx, src/app/product/[productId]/Info.tsx, src/components/Pagination.tsx, src/components/layout/Header.tsx, src/components/layout/HeaderSearch.tsx, src/components/review/ReviewBtnGroup.tsx
=> Refact/user auth페이지 최적화

src/app/payment/[userId]/page.tsx, src/app/users/[userId]/UserInfoSection.tsx
=> Refact/payment 최적화(짜잘한)

src/app/admin/product/addProduct/page.tsx, src/app/admin/product/page.tsx, src/data/sideTab.json
=> [feat/admin_product] admin product page url 수정 

src/app/admin/promotion/(Banner)/BannerForm.tsx, src/app/admin/promotion/(Banner)/BannerInfoTable.tsx, src/app/admin/promotion/(Carousel)/CarouselForm.tsx, src/app/admin/promotion/ManageBanner.tsx, src/app/admin/promotion/ManageCarousel.tsx, src/app/admin/promotion/page.tsx, src/app/api/storage/banner/[bannerName]/route.ts, src/app/api/storage/banner/route.ts, src/app/api/storage/carousel/[carouselId]/route.ts, src/app/api/storage/carousel/route.ts, src/app/users/[userId]/(tabContent)/UserRentList.tsx, src/components/CustomButton.tsx, src/components/InputImageView.tsx, src/components/layout/Article.tsx, src/data/sideTab.json, src/service/table/banner.ts, src/service/table/carousel.ts, src/types/db.ts
- 배너 관리
- 배너 수정
- 캐러셀 관리
- 캐러셀 수정
=> [feat/admin promotion] promotion 관리 페이지

src/app/admin/qna/Answer.tsx, src/app/admin/qna/Filter.tsx, src/app/admin/qna/QnaCard.tsx, src/app/admin/qna/page.tsx, src/app/api/admin/qna/[categoryId]/route.ts, src/app/api/admin/qna/route.ts, src/components/Pagination.tsx, src/data/sideTab.json, src/hook/useCustomMutation.ts, src/service/table/qna.ts
=> Feat/admin 어드민 QNA페이지를 만들었습니다.

src/app/api/user/[userId]/qna/route.ts, src/app/api/user/[userId]/rent/route.ts, src/app/api/user/[userId]/review/route.ts, src/app/users/[userId]/page.tsx
- dynamic import를 사용하여 300ms 성능 향상
- order을 적용하여 오름차순 내림차순을 적용 => 일관된 리스트 제공
=> [fix/mypage] 마이페이지 성능 및 리스트 정렬 적용

src/service/table/banner.ts, src/service/table/carousel.ts, src/service/table/category.ts, src/service/table/product.ts, src/service/table/qna.ts, src/service/table/region.ts, src/service/table/review.ts
- 배너, 카르셀, 상품 목록 등 revalidate 시간을 정해주었습니다.
=> fix : revalidate 시간 추가

src/app/auth/[find]/layout.tsx, src/components/Banner.tsx, src/components/Carousel.tsx, src/components/layout/Section.tsx
- section 마진을 10vh로 변경
- section이 없는 것에 section 적용
=> [style/all]

src/app/admin/product/page.tsx, src/app/api/user/[userId]/qna/route.ts, src/app/form/page.tsx, src/app/payment/[userId]/page.tsx, src/components/layout/PageBreadCrumb.tsx, src/utils/convertTime.ts, src/utils/useStorage.ts
=> [chore] 주석 제거

src/app/users/[userId]/EditUserInfo.tsx
프로필 수정 시 이미지 변경없이 이름만 변경하면 이미지URL이 잘못지정되는 문제를 해결했습니다.
=> [fix/mypage] 프로필 변경 시 이미지가 주소가 변경되는 문제 해결
